import math
from src.core.decorators.requireID import require_exists
from src.core.dependencies.uow import UnitOfWork
from src.exceptions.general_exceptions import CannotUpdate, ChangeAutoGenerated, ObjectIsArchived
from src.exceptions.payroll_exceptions import PayrollHasPayout, PayrollIsCancelled, PayrollNotFound
from src.repository.payroll.payroll_model import Payroll, PayrollStatus
from src.schemas.base import RequestAllObject
from src.schemas.payroll.create import PayrollCreateSchema
from src.schemas.payroll.update import PayrollUpdateSchema

class PayrollService():
    def __init__(self, uow: UnitOfWork):
        self.uow = uow
    
    @require_exists("employees", target_param = "employee_id")
    async def create(self, data: PayrollCreateSchema) -> Payroll:
        payrollData = data.model_dump()
        newObject = Payroll(**payrollData)
        return await self.uow.payrolls.create(newObject)
    
    async def update(self, data: PayrollUpdateSchema) -> Payroll:
        payroll = await self.uow.payrolls.get(data.id)
        if payroll is None: raise PayrollNotFound(data.id)
        if payroll.auto_generated: raise ChangeAutoGenerated(data.id, "payrolls")
        if payroll.payout_id: raise PayrollHasPayout(data.id)
        if payroll.archived: raise ObjectIsArchived(data.id, "payrolls")

        dataDict = data.model_dump(exclude = {"id"}, exclude_unset = True)

        result = await self.uow.payrolls.update(data.id, **dataDict)
        if not result: raise CannotUpdate(data.id, "payrolls")
        return result
    
    async def get(self, id: int) -> Payroll:
        result = await self.uow.payrolls.get(id)
        if not result: raise PayrollNotFound(id)
        return result
    
    async def get_many(self, ids: list[int]) -> list[Payroll]:
        return await self.uow.payrolls.get_by_ids(ids)
    
    async def get_all(self, data: RequestAllObject) -> dict:
        items, total_items = await self.uow.payrolls.get_all(data)

        total_pages = math.ceil(total_items / data.pageSize) if data.pageSize > 0 else 0
        
        return {
            "items": items,
            "page": data.page,
            "pageSize": data.pageSize,
            "totalItems": total_items,
            "totalPages": total_pages
        }
    
    async def delete(self, id: int):
        payroll = await self.uow.payrolls.get(id)
        if payroll is None: raise PayrollNotFound(id)
        if payroll.auto_generated: raise ChangeAutoGenerated(id, "payrolls")
        if payroll.payout_id: raise PayrollHasPayout(id)
        if not payroll.archived: raise ObjectIsArchived(id, "payrolls")

        await self.uow.payrolls.delete(id)

    async def cancel(self, id: int) -> Payroll:
        payroll = await self.uow.payrolls.get(id)
        if payroll is None: raise PayrollNotFound(id)
        if payroll.status == PayrollStatus.CANCELLED: raise PayrollIsCancelled(id)
        if payroll.auto_generated: raise ChangeAutoGenerated(id, "payrolls")
        if payroll.payout_id: raise PayrollHasPayout(id)
        if payroll.archived: raise ObjectIsArchived(id, "payrolls")

        result = await self.uow.payrolls.update(id, status = PayrollStatus.CANCELLED)
        if result is None: raise CannotUpdate(id, "payrolls")
        return result