"""empty message

Revision ID: 0262df89dade
Revises: a06960ab4ca7
Create Date: 2026-09-12 22:12:19.798901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0262df89dade'
down_revision: Union[str, Sequence[str], None] = 'a06960ab4ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('employees_phone_key'), 'employees', type_='unique')
    op.create_unique_constraint('uq_employee_phone', 'employees', ['phone', 'tenant_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_employee_phone', 'employees', type_='unique')
    op.create_unique_constraint(op.f('employees_phone_key'), 'employees', ['phone'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
