"""empty message

Revision ID: f360937b2771
Revises: 7d9cbf4309c8
Create Date: 2026-09-10 01:42:02.997737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f360937b2771'
down_revision: Union[str, Sequence[str], None] = '7d9cbf4309c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_auth_attempts',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_actor_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id', 'tenant_id'], ['staffs.id', 'staffs.tenant_id'], name='fk_staff_auth_attempts', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_staffAuthAttempts_tenant')
    )
    op.create_index(op.f('ix_staff_auth_attempts_staff_id'), 'staff_auth_attempts', ['staff_id'], unique=False)
    op.create_index(op.f('ix_staff_auth_attempts_status'), 'staff_auth_attempts', ['status'], unique=False)
    op.create_index(op.f('ix_staff_auth_attempts_tenant_id'), 'staff_auth_attempts', ['tenant_id'], unique=False)
    op.execute('CREATE EXTENSION IF NOT EXISTS citext')
    op.alter_column('tenants', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=postgresql.CITEXT(),
               existing_nullable=False)
    op.drop_constraint(op.f('tenants_name_key'), 'tenants', type_='unique')
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.create_unique_constraint(op.f('tenants_name_key'), 'tenants', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('tenants', 'name',
               existing_type=postgresql.CITEXT(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.execute('DROP EXTENSION IF EXISTS citext')
    op.drop_index(op.f('ix_staff_auth_attempts_tenant_id'), table_name='staff_auth_attempts')
    op.drop_index(op.f('ix_staff_auth_attempts_status'), table_name='staff_auth_attempts')
    op.drop_index(op.f('ix_staff_auth_attempts_staff_id'), table_name='staff_auth_attempts')
    op.drop_table('staff_auth_attempts')
    # ### end Alembic commands ###
