from .base import BaseAppException

class ObjectIsArchived(BaseAppException):
    statusCode = 409
    errorCode = "OBJECT_IS_ARCHIVED"
    def __init__(self, id: int, table: str):
        super().__init__(
            detail = f"Object ID {id} from {table} is archived",
            errorCode = self.errorCode,
            id = id,
            table = table
        )

class FieldCannotBeEmpty(BaseAppException):
    statusCode = 400
    errorCode = "FIELD_IS_EMPTY"
    def __init__(self, field: str):
        super().__init__(
            detail=f"Field {field} is empty",
            errorCode = self.errorCode,
            field = field
        )

class CannotUpdate(BaseAppException):
    statusCode = 404
    errorCode = "COULD_NOT_UPDATE"
    def __init__(self, id: int, table: str):
        super().__init__(
            detail = f"Could not update entity {id} from {table}",
            errorCode = self.errorCode,
            id = id
        )

class ValueCannotBeNegative(BaseAppException):
    statusCode = 409
    errorCode = "VALUE_CANNOT_BE_NEGATIVE"
    def __init__(self):
        super().__init__(
            detail=f"Value cannot be negative",
            errorCode = self.errorCode
        )

class PriceChangedReasonEmpty(BaseAppException):
    statusCode = 400
    errorCode = "PRICE_CHANGED_REASON_EMPTY"
    def __init__(self):
        super().__init__(
            detail = f"Required to provide price changed reason",
            errorCode = self.errorCode
        )

class PaymentCancelDueExpired(BaseAppException):
    statusCode = 409
    errorCode = "PAYMENT_CANCEL_DUE_EXPIRED"
    def __init__(self, expirationTime: int):
        super().__init__(
            detail = f"Payment cancel due time ({expirationTime} hours) has expired",
            errorCode = self.errorCode,
            expiration_time = expirationTime
        )

class ChangeAutoGenerated(BaseAppException):
    statusCode = 400
    errorCode = "CANNOT_CHANGE_MANUALLY_AUTO_GENERATED"
    def __init__(self, id: int, table: str):
        super().__init__(
            detail = f"Cannot manually change auto generated objects",
            errorCode = self.errorCode,
            id = id,
            table = table
        )